### ISSUE TITLE
Issue while converting to composition API from Vue 2

### ISSUE THREAD

**Issue by devikumar-r** [yoyo930021/vc2c#45]
SyntaxError: Identifier expected. (36:17)
 35 | import { useRouter } from "vue-router";
 **

> 36 | import { ref as , reactive as  } from "vue"

;**

at v node_modules\prettier\parser-typescript.js:1:14679)
    at _H (\node_modules\prettier\parser-typescript.js:49:10722)
    at Object.cH [as parse] (\node_modules\prettier\parser-typescript.js:49:11028)
    at Object.parse (\node_modules\prettier\index.js:7515:23)
    at coreFormat (\node_modules\prettier\index.js:8829:18)
    at formatWithCursor2 (\node_modules\prettier\index.js:9021:18)
    at \node_modules\prettier\index.js:38183:12
    at Object.format (\node_modules\prettier\index.js:38197:12)
    at prettify (\node_modules\prettier-eslint\dist\index.js:141:31)
    at format (\node_modules\prettier-eslint\dist\index.js:126:20) {
  loc: { start: { line: 36, column: 17 } },

**Comment by ThomasRitter75** [comment]
This bug report is nearly one year old. I have the same error. Is this project still active? Can I help debug this? I do not have more output with debugging enabled in the config.
